# Generated by Django 6.0.2 on 2026-02-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0005_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order',), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
